<a href="https://colab.research.google.com/github/Py7949/Data-Science-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

**Creating Numpy Arrays**

In [ ]:
#np.array
import numpy as np

a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
#2D and 3D
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#dtype
ZZ = np.array([1,2,3],dtype=complex)
print(ZZ)

[1.+0.j 2.+0.j 3.+0.j]


In [ ]:
ZZ = np.array([1,2,3],dtype=float)
print(ZZ)

[1. 2. 3.]


In [ ]:
ZZ = np.array([1,2,3],dtype=bool)
print(ZZ)

[ True  True  True]


In [ ]:
#np.arange
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape
np.arange(1,11).reshape(2,5)

np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
#np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np.random
np.random.random((3,4))

array([[0.10253544, 0.29095707, 0.07076715, 0.82538868],
       [0.73539907, 0.22472054, 0.06469364, 0.77551048],
       [0.50708019, 0.74841007, 0.18473458, 0.84813322]])

In [ ]:
#np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
  #np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Array Attributes**

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)



In [ ]:
# ndim
print(a1.ndim)

1


In [ ]:
a2.ndim

2

In [ ]:
print(a3.ndim)

3


In [ ]:
#shape
a1.shape

(10,)

In [ ]:
print(a2.shape)
a2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
#size
a3.size

8

In [ ]:
#itemsize
a3.itemsize

8

In [ ]:
a2.itemsize

8

In [ ]:
a1.itemsize

8

In [ ]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


**Changing Datatype**

In [ ]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**Array Operations**

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#Scalar Operation

#arithmatic

a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:

a1+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:

a2*2

array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.]])

In [ ]:
#Relational operator
a2 > 6

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# Vector
#Arithmatic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

**Array Function**

In [ ]:
a1 =np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[18., 64., 90.],
       [39., 34., 80.],
       [27.,  8., 24.]])

In [ ]:
#max/min/sum/prod
#0 -> col and 1 -> row
np.max(a1)

np.float64(90.0)

In [ ]:
np.sum(a1)

np.float64(384.0)

In [ ]:
np.min(a1)

np.float64(8.0)

In [ ]:
np.prod(a1)

np.float64(57015572889600.0)

In [ ]:
np.max(a1,axis=0)

array([39., 64., 90.])

In [ ]:
np.min(a1,axis=0)

array([18.,  8., 24.])

In [ ]:
np.max(a1,axis=1)

array([90., 80., 27.])

In [ ]:
#mean/median/std/var
np.mean(a1,axis=1)

array([57.33333333, 51.        , 19.66666667])

In [ ]:
np.var(a1,axis=0)

array([ 74.        , 523.55555556, 843.55555556])

In [ ]:
#trigonometric functions
np.sin(a1)

array([[-0.75098725,  0.92002604,  0.89399666],
       [ 0.96379539,  0.52908269, -0.99388865],
       [ 0.95637593,  0.98935825, -0.90557836]])

In [ ]:
#dot product
import numpy as np

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
res = np. dot(a2,a3)
print(res)

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [ ]:
# log and exponent
np.log(a2)

<ipython-input-10-8fd591372ef2>:2: RuntimeWarning: divide by zero encountered in log
  np.log(a2)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [ ]:
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [ ]:
#round/floor/ceil

np.round(np.random.random((2,3))*100)

array([[63., 58., 29.],
       [11., 41., 56.]])

**Indexing and Slicing**

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1[1]

np.int64(1)

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,2]

np.int64(6)

In [ ]:
 a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

np.int64(5)

In [ ]:
a3[0,1,0]

np.int64(2)

In [ ]:
a3[0,0,0]

np.int64(0)

In [ ]:
a3[1,1,1]

np.int64(7)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Slicing
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0,1]

array([3, 4, 5])

In [ ]:
a3[1,0:,1]

array([10, 13, 16])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

**Iterating**

In [ ]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


**Transpose**

In [ ]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

**Ravel**

In [ ]:

a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

**Stacking**

In [ ]:
# Horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
#Vertical Stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

 **Splitting**

In [ ]:
#Horizontal split
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
#Vertical split
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

**Numpy array vs Python lists**

In [ ]:
#speed
#list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]
c = []
import time
start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)




2.524315118789673


In [ ]:
#numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)
start = time.time()
c = a + b
print(time.time()-start)

0.04006242752075195


In [ ]:
2.52/0.04

63.0

In [ ]:
#Memory
a = [i for i in range(10000000)]
import sys
sys.getsizeof(a)

89095160

In [ ]:
a = np.arange(10000000,dtype= np.int8)
sys.getsizeof(a)

10000112

**Advanced Indexing**

In [ ]:
#Normal Indexing and slicing
a = np.arange(24).reshape(6,4)
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a[1,2]

np.int64(6)

In [ ]:
#Fancy Indexing
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[[0,2,3]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [ ]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [ ]:
##Boolean Indexing
import numpy as np
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[57, 91,  4, 68],
       [53, 86, 41, 74],
       [ 3,  1, 25,  3],
       [12, 46, 94, 11],
       [ 7, 12, 58, 32],
       [23, 17, 71, 64]])

In [ ]:
#find all number greater than 50
a > 50

array([[ True,  True, False,  True],
       [ True,  True, False,  True],
       [False, False, False, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True,  True]])

In [ ]:
a[a > 50]

array([57, 91, 68, 53, 86, 74, 94, 58, 71, 64])

In [ ]:
# find all numbers greater than 50 and even
a[(a > 50) & (a % 2 == 0)]


array([68, 86, 74, 94, 58, 64])

In [ ]:
#find all numbers ot divisble by 7
a[a % 7 != 0]

array([57,  4, 68, 53, 86, 41, 74,  3,  1, 25,  3, 12, 46, 94, 11, 12, 58,
       32, 23, 17, 71, 64])